start-bd:
	json-server --watch ../json-servers/bd.json

start-bdParcs:
	json-server --watch ../json-servers/bdParcs.json

open-bd:
	code ../json-servers/bd.json

open-bdParcs:
	code ../json-servers/bdParcs.json